name: Build and Deploy to Pages

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3
        id: pages
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'yarn'
      - run:
          npm install -g yarn
          yarn set version berry
          yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment